name: CI Workflow

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm ci 
          npm run build 

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: dist  # Directorio donde Vite genera los archivos de producción
          production-only: true
          deploy-message: ${{ github.event_name }}

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}