name: CI Workflow

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci 
          npm run build 

      - name: Deploy to Netlify 🚀
        uses: data-intuitive/netlify-deploy-site@v1
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          dir: 'dist'
          site: ${{ secrets.NETLIFY_SITE_ID }}
          prod: true
          message: 'Deploy production ${{ github.ref }}'